version: '2'
services:
  web:
    extends:
      file: common-services.yml
      service: common
    ports:
      - "80:80"
    environment:
      NEWRELIC_APP_NAME: Majordomo-web

  cycles:
    extends:
      file: common-services.yml
      service: common
    command: php cycle.php
    environment:
      NEWRELIC_APP_NAME: Majordomo-bgtasks

  # Backup DB to Amazon S3 every day
  mysql_backup:
    image: schickling/mysql-backup-s3
    environment:
      S3_ACCESS_KEY_ID: xxx
      S3_SECRET_ACCESS_KEY: xxx
      S3_BUCKET: xxx
      S3_PREFIX: xxx
      MYSQL_HOST: 192.168.0.4
      MYSQL_USER: majordomo_sql
      MYSQL_PASSWORD: xxx
      MYSQLDUMP_DATABASE: db_terminal
      SCHEDULE: '@daily'

  # Backup all files of /etc/majordomo to Amazon S3 every 3 days
  config_backup:
    image: outcoldman/backup:latest
    environment:
      BACKUP_FIND_OPTIONS: /backup
      BACKUP_PREFIX: docker-compose
      BACKUP_AWS_S3_PATH: s3://xxx/backup/configs/
      BACKUP_AWS_KEY: xxx
      BACKUP_AWS_SECRET: xxx
      BACKUP_TIMEZONE: Europe/Kiev
      BACKUP_CRON_SCHEDULE: '0 2 */3 * *'
    volumes:
      - /etc/majordomo:/backup

  # Send majordomo logs to sumologic.com
  majordomo_logs:
    image: sumologic/collector:latest-file
    command: xxxxxxx xxxxxxxxxxxxxxxxxx
    volumes:
      - /var/log/majordomo/debmes:/tmp/clogs

  # Send mysql logs to sumologic.com
  mysql_logs:
    image: sumologic/collector:latest-file
    command: xxxxxxx xxxxxxxxxxxxxxxxxx
    volumes:
      - /var/log/mysql:/tmp/clogs

  # UI for managing docker containers
  # Will be available on port 88
  dockerui:
    image: uifd/ui-for-docker
    ports:
      - "88:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
